dataset: "EMNS"

path:
  corpus_path: "/Datasets/EMNS"
  lexicon_path: "lexicon/librispeech-lexicon.txt"
  raw_path: "./raw_data/EMNS"
  preprocessed_path: "./preprocessed_data/EMNS"

preprocessing:
  val_size: 100
  text:
    text_cleaners: ["english_cleaners"]
    language: "en"
  audio:
    sampling_rate: 48000
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  emoton:
    feature: "frame_level" # support 'phoneme_level' or 'frame_level'